{
    id: "hikers-rock-pool-waterfall",
    src: "/images/nov-2025/hikers-rock-pool-waterfall.webp",
    alt: "Hikers exploring a rock pool beneath a cascading waterfall",
    title: "Rock Pool Waterfall Hike",
    category: "landscapes",
  },
  {
    id: "hikers-walking-rocky-beach",
    src: "/images/nov-2025/hikers-walking-rocky-beach.webp",
    alt: "Hikers walking along a rugged rocky beach shoreline",
    title: "Rocky Beach Walk",
    category: "landscapes",
  },
  {
    id: "historic-stone-ruins-tour",
    src: "/images/nov-2025/historic-stone-ruins-tour.webp",
    alt: "Visitors exploring ancient stone ruins with scenic surroundings",
    title: "Historic Stone Ruins Tour",
    category: "culture",
  },
  {
    id: "kayaking",
    src: "/images/nov-2025/kayaking.webp",
    alt: "Kayaker paddling through calm waters surrounded by nature",
    title: "Kayaking Adventure",
    category: "adventure",
  },
  {
    id: "layered-cliff-formations",
    src: "/images/nov-2025/layered-cliff-formations.webp",
    alt: "Dramatic layered cliff formations with contrasting geological textures",
    title: "Layered Cliffs",
    category: "landscapes",
  },
  {
    id: "orange-rondavels",
    src: "/images/nov-2025/orange-rondavels.webp",
    alt: "Traditional rondavel huts painted in warm orange tones",
    title: "Orange Rondavels",
    category: "culture",
  },
  {
    id: "phiwani-homestay",
    src: "/images/nov-2025/phiwani-homestay.webp",
    alt: "Rural homestay buildings nestled in natural surroundings",
    title: "Phiwani Homestay",
    category: "culture",
  },
  {
    id: "red-dunes",
    src: "/images/nov-2025/red-dunes.webp",
    alt: "Rolling red sand dunes under open skies",
    title: "Red Dunes",
    category: "landscapes",
  },
  {
    id: "red-earth-hillside",
    src: "/images/nov-2025/red-earth-hillside.webp",
    alt: "Hillside covered in striking red earth and sparse vegetation",
    title: "Red Earth Hillside",
    category: "landscapes",
  },
  {
    id: "red-sand-dunes",
    src: "/images/nov-2025/red-sand-dunes.webp",
    alt: "Sweeping red sand dunes shaped by winds",
    title: "Red Sand Dunes",
    category: "landscapes",
  },
  {
    id: "river-landscape",
    src: "/images/nov-2025/river-landscape.webp",
    alt: "Wide river flowing through rolling terrain",
    title: "River Landscape",
    category: "landscapes",
  },
  {
    id: "rocky-coastline-tidal-pools",
    src: "/images/nov-2025/rocky-coastline-tidal-pools.webp",
    alt: "Rocky coastline with clear tidal pools and ocean swells",
    title: "Tidal Pools on the Coast",
    category: "landscapes",
  },
  {
    id: "rocky-stream-cliff-landscape",
    src: "/images/nov-2025/rocky-stream-cliff-landscape.webp",
    alt: "Stream winding through cliffs and rugged rocky terrain",
    title: "Rocky Stream Valley",
    category: "landscapes",
  },
  {
    id: "rolling-grassland-trail",
    src: "/images/nov-2025/rolling-grassland-trail.webp",
    alt: "Trail cutting across vast rolling grasslands",
    title: "Grassland Trail",
    category: "landscapes",
  },
  {
    id: "rondavel-hut-chickens-yard",
    src: "/images/nov-2025/rondavel-hut-chickens-yard.webp",
    alt: "Chickens roaming freely around a rondavel hut",
    title: "Rondavel and Chickens",
    category: "culture",
  },
  {
    id: "rusty-shipwreck-boiler-beach",
    src: "/images/nov-2025/rusty-shipwreck-boiler-beach.webp",
    alt: "Rusty shipwreck boiler resting on a remote beach",
    title: "Shipwreck Boiler",
    category: "history",
  },
  {
    id: "sea-arch-rock-formation",
    src: "/images/nov-2025/sea-arch-rock-formation.webp",
    alt: "Natural sea arch carved by ocean waves",
    title: "Sea Arch",
    category: "landscapes",
  },
  {
    id: "still-river-hills-reflection",
    src: "/images/nov-2025/still-river-hills-reflection.webp",
    alt: "Glasslike river reflecting surrounding hills",
    title: "Hill Reflections",
    category: "landscapes",
  },
  {
    id: "tall-waterfall",
    src: "/images/nov-2025/tall-waterfall.webp",
    alt: "Tall waterfall cascading down steep cliffs",
    title: "Tall Waterfall",
    category: "landscapes",
  },
  {
    id: "tide-pools-sea-urchins",
    src: "/images/nov-2025/tide-pools-sea-urchins.webp",
    alt: "Tidal pool filled with sea urchins and marine life",
    title: "Tidal Pool Sea Urchins",
    category: "wildlife",
  },
  {
    id: "tranquil-river-hills",
    src: "/images/nov-2025/tranquil-river-hills.webp",
    alt: "Quiet river flowing past rolling green hills",
    title: "Tranquil River",
    category: "landscapes",
  },
  {
    id: "tranquil-river-rocky-hills",
    src: "/images/nov-2025/tranquil-river-rocky-hills.webp",
    alt: "River bordered by rocky hills and dramatic terrain",
    title: "Rocky Hills River",
    category: "landscapes",
  },
  {
    id: "waterfall-bluff-ocean-cliff",
    src: "/images/nov-2025/waterfall-bluff-ocean-cliff.webp",
    alt: "Waterfall flowing directly into the ocean from a cliff",
    title: "Ocean Cliff Waterfall",
    category: "landscapes",
  },
  {
    id: "waterfall-rock-pool",
    src: "/images/nov-2025/waterfall-rock-pool.webp",
    alt: "Waterfall feeding into a clear natural rock pool",
    title: "Rock Pool Waterfall",
    category: "landscapes",
  },
  {
    id: "woman-drinking-tea-patio",
    src: "/images/nov-2025/woman-drinking-tea-patio.webp",
    alt: "Woman enjoying tea while seated on a patio",
    title: "Tea on the Patio",
    category: "people",
  }
]
